### ISSUE TITLE
Unexpected status byte 0x80 and Warning: Unknown Meta MIDI Event: 10

### ISSUE THREAD

**Issue by Blizzsuxx** [timwedde/py_midicsv#14]
`
File "midiToText.py", line 10, in convertMidiFile
    csv_string = pm.midi_to_csv(midiName)
  File "/home/user/anaconda3/lib/python3.8/site-packages/py_midicsv/midicsv.py", line 22, in parse
    pattern = read_midifile(file)
  File "/home/user/anaconda3/lib/python3.8/site-packages/py_midicsv/midi/fileio.py", line 221, in read_midifile
    return read_midifile(inp)
  File "/home/user/anaconda3/lib/python3.8/site-packages/py_midicsv/midi/fileio.py", line 223, in read_midifile
    return reader.read(midifile)
  File "/home/user/anaconda3/lib/python3.8/site-packages/py_midicsv/midi/fileio.py", line 45, in read
    self.parse_track(midifile, track)
  File "/home/user/anaconda3/lib/python3.8/site-packages/py_midicsv/midi/fileio.py", line 87, in parse_track
    event = self.parse_midi_event(trackdata)
  File "/home/user/anaconda3/lib/python3.8/site-packages/py_midicsv/midi/fileio.py", line 133, in parse_midi_event
    data = [trackdata.get_data_byte() for _ in range(cls.length)]
  File "/home/user/anaconda3/lib/python3.8/site-packages/py_midicsv/midi/fileio.py", line 133, in <listcomp>
    data = [trackdata.get_data_byte() for _ in range(cls.length)]
  File "/home/user/anaconda3/lib/python3.8/site-packages/py_midicsv/midi/fileio.py", line 36, in get_data_byte
    self.assert_data_byte(byte)
  File "/home/user/anaconda3/lib/python3.8/site-packages/py_midicsv/midi/fileio.py", line 29, in assert_data_byte
    assert data & 0x80 == 0, self.errmsg("Unexpected status byte", data)
AssertionError: Unexpected status byte 0x80 at position 35078
`

https://easyupload.io/zz2wf6 midi file that causes the issue

when i comment out the assert the conversion passes, though i get a different error later with a different midi

`
Traceback (most recent call last):
  File "midiToText.py", line 35, in <module>
    convertMidiFolderOfFolders(midiName)
  File "midiToText.py", line 20, in convertMidiFolderOfFolders
    convertMidiFolder(path + "/" + midiName)
  File "midiToText.py", line 16, in convertMidiFolder
    convertMidiFile(path + "/" + midiName)
  File "midiToText.py", line 10, in convertMidiFile
    csv_string = pm.midi_to_csv(midiName)
  File "/home/user/anaconda3/lib/python3.8/site-packages/py_midicsv/midicsv.py", line 22, in parse
    pattern = read_midifile(file)
  File "/home/user/anaconda3/lib/python3.8/site-packages/py_midicsv/midi/fileio.py", line 221, in read_midifile
    return read_midifile(inp)
  File "/home/user/anaconda3/lib/python3.8/site-packages/py_midicsv/midi/fileio.py", line 223, in read_midifile
    return reader.read(midifile)
  File "/home/user/anaconda3/lib/python3.8/site-packages/py_midicsv/midi/fileio.py", line 45, in read
    self.parse_track(midifile, track)
  File "/home/user/anaconda3/lib/python3.8/site-packages/py_midicsv/midi/fileio.py", line 87, in parse_track
    event = self.parse_midi_event(trackdata)
  File "/home/user/anaconda3/lib/python3.8/site-packages/py_midicsv/midi/fileio.py", line 103, in parse_midi_event
    raise Warning("Unknown Meta MIDI Event: " + repr(cmd))
Warning: Unknown Meta MIDI Event: 10
`
https://easyupload.io/8y3mz2

file that causes the issue

**Comment by timwedde** [comment]
Thanks for reporting this, I'll be taking a look at this issue over the weekend.
My first thought would be a MIDI file that doesn't quite conform to the spec, but there could also be a bug in the parser, so I'll be investigating this and let you know what I turn up.

**Comment by timwedde** [comment]
Hey there, a quick update on this: As I suspected, it does indeed turn out that your first MIDI file contains a value that is out of spec. Specifically, this is a CC instruction with a value of 128, whereas the limit is 127. This is out of spec and thus causes an error.
Your second MIDI file errors out because, like it says, there is an unknown Meta event in a particular track. I originally treated unknown events as errors, but have since learned that MIDI file parsers should ignore unknown Meta events when they occur.

To remedy this situation I am now doing the following:
- Treat unknown Meta events as warnings in all cases to be compliant with the spec for parsers. This means you'll receive a warning printed to stderr, but the process will complete successfully nonetheless. However, the unknown event will not be present in the output.
- Add a "non-strict" mode to the MIDI to CSV conversion direction. When disabled (the default), the library will behave as before, raising Exceptions on parsing errors. When given, however, it will instead print these exceptions to stderr and continue, skipping the affected events (hence they will not be present in the output).

I am also adding a third thing that will likely come in handy in more general terms: A MIDI validator which checks basic things per message (length, checksum, value ranges etc). This will work like other exceptions depending on whether "non-strict" mode is active or not, either raising an Exception or printing a warning to stderr including the actual value and position in the bytestream.

This should hopefully satisfy both the people who desire hard exceptions on MIDI failures as well as the people who just care about getting as much data out as possible, even if some things are broken. The validator should hopefully also help with debugging corrupted MIDI files to some extent.

I already pushed some work on this and will flesh this approach out over the weekend, so hopefully I can push a new major version with these features included soon.

**Comment by Blizzsuxx** [comment]
thanks a lot, I'm trying to train gpt-2 to generate midi files and your tool has helped a ton

**Comment by timwedde** [comment]
That's good to hear, glad it could be of some use!
Your use case is actually quite similar to mine, I have started on a related adventure a couple of days back. I wish you good luck on your quest.

I'll post updates here once some more progress is being made and when the new version is actually released.

**Comment by timwedde** [comment]
Alright, a new release has been made. Feel free to upgrade and check it out.
Let me know if you run into any issues.

For CLI invocation there is now a new `-n` flag (for `nostrict`) and for library usage you may supply `strict=False` to the usual methods to turn exceptions into warnings where possible.

**Comment by Blizzsuxx** [comment]
thanks a lot
