### ISSUE TITLE
Event length mismatch for PortEvent

### ISSUE THREAD

**Issue by klausnielsen** [timwedde/py_midicsv#18]
Hi Tim,
Hope you can help me out. The package looks super cool, and I'm very much looking forward to working with it.
I'm having trouble getting it to work though. Have tried both as library in Python and as command prompts, but the error message is the same. I have also tried with different midi files (different sizes and from different sequencing software), and the error message still reads "Event length mismatch for PortEvent at position 65". Can you see, what I'm doing wrong?
I'm using:
Python 3.12.3
py-midicsv 4.1.0
windows 11

Cheers
Klaus
```ruby
>>> csv_string = pm.midi_to_csv("test2B.mid")
Traceback (most recent call last):
  File "C:\Users\klsnl\Miniconda3\envs\py3_env\Lib\site-packages\py_midicsv\midi\fileio.py", line 134, in parse_midi_event
    event.check()
  File "C:\Users\klsnl\Miniconda3\envs\py3_env\Lib\site-packages\py_midicsv\midi\events.py", line 64, in check
    assert len(self.data) == self.length, f"Event length mismatch for {self.__class__.__name__}"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Event length mismatch for PortEvent

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\klsnl\Miniconda3\envs\py3_env\Lib\site-packages\py_midicsv\midicsv.py", line 22, in parse
    pattern = read_midifile(file, strict)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\klsnl\Miniconda3\envs\py3_env\Lib\site-packages\py_midicsv\midi\fileio.py", line 275, in read_midifile
    return read_midifile(inp, strict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\klsnl\Miniconda3\envs\py3_env\Lib\site-packages\py_midicsv\midi\fileio.py", line 277, in read_midifile
    return reader.read(midifile, strict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\klsnl\Miniconda3\envs\py3_env\Lib\site-packages\py_midicsv\midi\fileio.py", line 66, in read
    self.parse_track(midifile, track, strict)
  File "C:\Users\klsnl\Miniconda3\envs\py3_env\Lib\site-packages\py_midicsv\midi\fileio.py", line 108, in parse_track
    event = self.parse_midi_event(trackdata, strict)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\klsnl\Miniconda3\envs\py3_env\Lib\site-packages\py_midicsv\midi\fileio.py", line 136, in parse_midi_event
    warn_or_error(f"{e} at position {trackdata.pos()}", strict, is_parse=False)
  File "C:\Users\klsnl\Miniconda3\envs\py3_env\Lib\site-packages\py_midicsv\midi\fileio.py", line 23, in warn_or_error
    raise ValidationError(text)
py_midicsv.midi.fileio.ValidationError: Event length mismatch for PortEvent at position 65
```

**Comment by timwedde** [comment]
I'll need a bit more information to track down the source of this issue:
- What version of py_midicsv are you using?
- Could you upload one or two of the MIDI files that fail to work on your machine? This will allow me to attempt to replicate this issue locally.

**Comment by klausnielsen** [comment]
Thanks for the quick and helpful response, Tim. I'm using 4.1.0 of py_midicsv (downloaded today). GitHub wont allow me to attach midi files, but I've uploaded them to WeTransfer instead: https://we.tl/t-kDvLgTdH08
Cheers

**Comment by timwedde** [comment]
Thanks, that's very helpful. I can confirm that I'm able to reproduce the issue on my end, will start debugging this and working on a fix. I'll update this issue once I know more!

**Comment by timwedde** [comment]
Good news, I managed to fix the bug (it was a simple oversight, apologies). I'm gonna be releasing `4.1.1` right now to get this fix out to everyone. Let me know if this resolves your issue and if not, feel free to reopen!

**Comment by klausnielsen** [comment]
thanks Tim!! for super quick action on this - looking forward to testing it out
